# Site settings
title: Rickter Scale
description: "An in-depth movie scoring record by and for Rick Sear"
keywords:
skills: "An in-depth record of the movies I've watched"
meta_author: searri
baseurl: /rickter-scale

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 833ec4 #80B3FF
  primary-rgb: "131,62,196" #"128,179,255"
  secondary: 413ec4 #FD6E8A
  secondary-dark: 252370 #A2122F

# Footer settings
footer:
  copyright: Rick Sear

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
