on:
  push:
    branches: [ main ]
    paths:
      - 'movie-jsons/*'

jobs:
  run-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Run movie markdown rebuild script
        run: |
          COMMIT_MESSAGE_PHRASE="NEW MOVIE:"
          if [[ $GITHUB_SHA =~ ^"$COMMIT_MESSAGE_PHRASE" ]]; then
            python build_movies.py
            git add -A
            git commit -m "Automatic movie rebuild"
          fi
